# This is a basic workflow to help you get started with Actions

name: Large-file-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
      - uses: actions/cache@v3
        with:
          path: cache-folder
          key: ${{ runner.os }}-large-key

      - name: Generate a file
        run: |
          mkdir -p cache-folder
          cd cache-folder
          if [ ! -f "10GB.bin" ]; then
            dd if=/dev/urandom of=10GB.bin count=10000 bs=1048576
          fi
          cat 10GB.bin | openssl dgst -sha256 > sha256.txt

      - uses: actions/upload-artifact@v3
        with:
          name: large
          path: "cache-folder/10GB.bin"
